package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class AverageAggregation_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements PathwayAggregationMethod_BehaviorDescriptor {
  public AverageAggregation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.AverageAggregation";
  }
}
