package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CoxRegProperties_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CoxRegProperties_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.CoxRegProperties";
  }
}
