package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CoxRegParameters_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CoxRegParameters_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.CoxRegParameters";
  }
}
