package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Evaluate_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Evaluate_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.Evaluate";
  }
}
