package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class FCP_LogitBoost_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Classification_BehaviorDescriptor {
  public FCP_LogitBoost_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.FCP_LogitBoost";
  }
}
