package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class FeatureSelectionInfo_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "maxIntermediateFeatures", "" + (400));

    SNode numFeature = SConceptOperations.createNewNode("org.campagnelab.bdval.structure.Integer", null);
    SPropertyOperations.set(numFeature, "value", "" + (20));
    ListSequence.fromList(SLinkOperations.getTargets(thisNode, "numberOfFeatures", true)).addElement(numFeature);

    SNode fsFold = SConceptOperations.createNewNode("org.campagnelab.bdval.structure.FeatureSelectionFoldTrue", null);
    ListSequence.fromList(SLinkOperations.getTargets(thisNode, "featureSelectionFold", true)).addElement(fsFold);

    SNode fsCombo = SConceptOperations.createNewNode("org.campagnelab.bdval.structure.FeatureSelectionStrategy", null);
    SNode fs = SConceptOperations.createNewNode("org.campagnelab.bdval.structure.Ttest", null);
    SLinkOperations.setTarget(fsCombo, "step1", fs, true);
    ListSequence.fromList(SLinkOperations.getTargets(thisNode, "strategy", true)).addElement(fsCombo);
  }
}
