package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FeatureSelectionChoices_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public FeatureSelectionChoices_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.FeatureSelectionChoices";
  }
}
