package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface FeatureSelectionOption_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
