package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class FeatureSelectionFoldTrue_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "name", "use-feature-selection-fold=true");
    SPropertyOperations.set(thisNode, "value", "" + (true));
  }
}
