package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FloatRange_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public FloatRange_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.FloatRange";
  }
}
