package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class GenelistRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public GenelistRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.GenelistRef";
  }
}
