package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class InputIds_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public InputIds_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.InputIds";
  }
}
