package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LoggedArray_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements ArrayParameter_BehaviorDescriptor {
  public LoggedArray_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.LoggedArray";
  }
}
