package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class PathwayProperties_Behavior {
  public static void init(SNode thisNode) {
    SNode PCA = SConceptOperations.createNewNode("org.campagnelab.bdval.structure.PCAAggregation", null);
    SLinkOperations.setTarget(thisNode, "aggregationMethod", PCA, true);
  }
}
