package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Properties_Behavior {
  public static void init(SNode thisNode) {
    SNode outputDirectory = SConceptOperations.createNewNode("org.campagnelab.bdval.structure.Directory", null);
    SPropertyOperations.set(outputDirectory, "directoryLocation", System.getProperty("user.home") + "/BDValProjects");
    SLinkOperations.setTarget(thisNode, "outputDirectory", outputDirectory, true);
  }
}
