package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Properties_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "outputLocation", System.getProperty("user.home") + "/BDValProjects");
  }
}
