package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SVMProperties_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SVMProperties_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.SVMProperties";
  }
}
