package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SVMTuneCProperties_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SVMTuneCProperties_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.SVMTuneCProperties";
  }
}
