package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TTestProperties_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TTestProperties_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.TTestProperties";
  }
}
