package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Ttest_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "name", "ttest");
    SPropertyOperations.set(thisNode, "addoptions", "addoption required:alpha:confidence level for T-test\n");
    SPropertyOperations.set(thisNode, "sequenceCommand", " t-test");
    SPropertyOperations.set(thisNode, "sequenceInfo", " --alpha %alpha%");
    SPropertyOperations.set(thisNode, "sequenceNumFeatures", " --report-max-probes");
    SPropertyOperations.set(thisNode, "otherOptions", " --alpha ${ttest-alpha}");

  }
}
