package org.campagnelab.bdval.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TtestProperties_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TtestProperties_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.bdval.structure.TtestProperties";
  }
}
