package org.campagnelab.bdval.plugin;

/*Generated by MPS */

import jetbrains.mps.make.facet.IFacet;
import java.util.List;
import jetbrains.mps.make.facet.ITarget;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.make.resources.IPropertiesPersistence;
import jetbrains.mps.make.facet.ITargetEx2;
import jetbrains.mps.make.script.IJob;
import jetbrains.mps.make.script.IResult;
import jetbrains.mps.make.resources.IResource;
import jetbrains.mps.make.script.IJobMonitor;
import jetbrains.mps.make.resources.IPropertiesAccessor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.util.ProgressMonitor;
import jetbrains.mps.smodel.resources.TResource;
import org.apache.log4j.Level;
import jetbrains.mps.make.script.IFeedback;
import jetbrains.mps.project.facets.JavaModuleFacet;
import jetbrains.mps.vfs.IFile;
import jetbrains.mps.util.SNodeOperations;
import java.io.File;
import jetbrains.mps.util.FileUtil;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.make.script.IConfig;
import java.util.Map;
import jetbrains.mps.make.script.IPropertiesPool;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class CopyXML_Facet extends IFacet.Stub {
  private List<ITarget> targets = ListSequence.fromList(new ArrayList<ITarget>());
  private IFacet.Name name = new IFacet.Name("org.campagnelab.bdval.CopyXML");

  public CopyXML_Facet() {
    ListSequence.fromList(targets).addElement(new CopyXML_Facet.Target_copy());
  }

  public Iterable<ITarget> targets() {
    return targets;
  }

  public Iterable<IFacet.Name> optional() {
    return null;
  }

  public Iterable<IFacet.Name> required() {
    return Sequence.fromArray(new IFacet.Name[]{new IFacet.Name("jetbrains.mps.lang.core.TextGen")});
  }

  public Iterable<IFacet.Name> extended() {
    return null;
  }

  public IFacet.Name getName() {
    return this.name;
  }

  public IPropertiesPersistence propertiesPersistence() {
    return new CopyXML_Facet.TargetProperties();
  }

  public static class Target_copy implements ITargetEx2 {
    private static final ITarget.Name name = new ITarget.Name("org.campagnelab.bdval.CopyXML.copy");

    public Target_copy() {
    }

    public IJob createJob() {
      return new IJob.Stub() {
        @Override
        public IResult execute(final Iterable<IResource> rawInput, final IJobMonitor monitor, final IPropertiesAccessor pa, @NotNull final ProgressMonitor progressMonitor) {
          Iterable<IResource> _output_lne71d_a0a = null;
          final Iterable<TResource> input = (Iterable<TResource>) (Iterable) rawInput;
          switch (0) {
            case 0:
              if (LOG.isEnabledFor(Level.WARN)) {
                LOG.warn("Invoked CopyXML");
              }
              _output_lne71d_a0a = Sequence.fromIterable(_output_lne71d_a0a).concat(Sequence.fromIterable(Sequence.<IResource>singleton(new CopyXMLTuple(null, null))));
              progressMonitor.start("Copying XML files", 1);
              monitor.reportFeedback(new IFeedback.INFORMATION(String.valueOf("Copying XML files")));
              int counter = 0;
              for (TResource tres : Sequence.fromIterable(input)) {
                JavaModuleFacet javaFacet = tres.module().getFacet(JavaModuleFacet.class);
                IFile classesGenFolder = javaFacet.getClassesGen().getDescendant(SNodeOperations.getModelLongName(tres.modelDescriptor()).replace(".", "/"));
                monitor.reportFeedback(new IFeedback.INFORMATION(String.valueOf("Class Gen Folder: " + classesGenFolder)));
                File sourceFolder;
                sourceFolder = new File(classesGenFolder.getPath());
                monitor.reportFeedback(new IFeedback.INFORMATION(String.valueOf("Source Folder: " + sourceFolder)));
                FileUtil.copyFile(new File(sourceFolder + "/" + ".xml"), new File(""));
                counter++;

                String targetFolder = null;
                for (SNode root : tres.modelDescriptor().getRootNodes()) {
                  monitor.reportFeedback(new IFeedback.INFORMATION(String.valueOf("Tres Root Node")));
                  {
                    SNode project = root;
                    if (jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations.isInstanceOf(project, "org.campagnelab.bdval.structure.Project")) {
                      SNode p = jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations.cast(root, "org.campagnelab.bdval.structure.Project");
                      targetFolder = SPropertyOperations.getString(SLinkOperations.getTarget(p, "properties", true), "outputLocation") + SPropertyOperations.getString(p, "name").replaceAll("\\s", "");
                      monitor.reportFeedback(new IFeedback.INFORMATION(String.valueOf("targetFolder: " + targetFolder)));
                      File targetFile = new File(targetFolder);
                      for (File fileInFolder : sourceFolder.listFiles()) {
                        FileUtil.copyFile(fileInFolder, targetFile);
                      }
                    }
                  }
                }
                _output_lne71d_a0a = Sequence.fromIterable(_output_lne71d_a0a).concat(Sequence.fromIterable(Sequence.<IResource>singleton(tres)));
              }
              progressMonitor.done();
              return new IResult.SUCCESS(_output_lne71d_a0a);
            default:
              return new IResult.SUCCESS(_output_lne71d_a0a);
          }
        }
      };
    }

    public IConfig createConfig() {
      return null;
    }

    public Iterable<ITarget.Name> notAfter() {
      return null;
    }

    public Iterable<ITarget.Name> after() {
      return Sequence.fromArray(new ITarget.Name[]{new ITarget.Name("jetbrains.mps.lang.core.TextGen.textGen")});
    }

    public Iterable<ITarget.Name> notBefore() {
      return null;
    }

    public Iterable<ITarget.Name> before() {
      return Sequence.fromArray(new ITarget.Name[]{new ITarget.Name("jetbrains.mps.make.facets.Make.reconcile")});
    }

    public ITarget.Name getName() {
      return name;
    }

    public boolean isOptional() {
      return false;
    }

    public boolean requiresInput() {
      return true;
    }

    public boolean producesOutput() {
      return false;
    }

    public Iterable<Class<? extends IResource>> expectedInput() {
      List<Class<? extends IResource>> rv = ListSequence.fromList(new ArrayList<Class<? extends IResource>>());
      ListSequence.fromList(rv).addElement(TResource.class);
      return rv;
    }

    public Iterable<Class<? extends IResource>> expectedOutput() {
      return null;
    }

    public <T> T createParameters(Class<T> cls) {
      return null;
    }

    public <T> T createParameters(Class<T> cls, T copyFrom) {
      T t = createParameters(cls);
      return t;
    }

    public int workEstimate() {
      return 400;
    }
  }

  public static class TargetProperties implements IPropertiesPersistence {
    public TargetProperties() {
    }

    public void storeValues(Map<String, String> store, IPropertiesPool properties) {
    }

    public void loadValues(Map<String, String> store, IPropertiesPool properties) {
      try {
      } catch (RuntimeException re) {
      }
    }
  }

  protected static Logger LOG = LogManager.getLogger(CopyXML_Facet.class);
}
