package org.campagnelab.bdval.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.io.File;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.messageTargets.PropertyMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.campagnelab.bdval.behavior.Properties_Behavior;
import jetbrains.mps.smodel.SModelUtil_new;

public class Check_Properties_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public Check_Properties_NonTypesystemRule() {
  }

  public void applyRule(final SNode properties, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (isNotEmptyString(SPropertyOperations.getString(properties, "bdvalLocation")) && !(new File(SPropertyOperations.getString(properties, "bdvalLocation")).isDirectory())) {
      {
        MessageTarget errorTarget = new NodeMessageTarget();
        errorTarget = new PropertyMessageTarget("bdvalLocation");
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(properties, "BDVal installation directory is not correct", "r:03143f03-46ae-4107-a067-34f5026aa223(org.campagnelab.bdval.typesystem)", "290469645492819265", null, errorTarget);
      }
    }
    if (isNotEmptyString(SPropertyOperations.getString(properties, "outputLocation")) && !(new File(SPropertyOperations.getString(properties, "outputLocation")).isDirectory())) {
      {
        MessageTarget errorTarget = new NodeMessageTarget();
        errorTarget = new PropertyMessageTarget("outputLocation");
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(properties, "Output location does not exist", "r:03143f03-46ae-4107-a067-34f5026aa223(org.campagnelab.bdval.typesystem)", "290469645492820864", null, errorTarget);
      }
    }
    List<String> aggregationMethods = ListSequence.fromListAndArray(new ArrayList<String>(), "average", "PCA");
    if (!(ListSequence.fromList(aggregationMethods).contains(SPropertyOperations.getString(properties, "pathwayAggregationMethod")))) {
      {
        MessageTarget errorTarget = new NodeMessageTarget();
        errorTarget = new PropertyMessageTarget("pathwayAggregationMethod");
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(properties, "Pathway Aggregation Method invalid", "r:03143f03-46ae-4107-a067-34f5026aa223(org.campagnelab.bdval.typesystem)", "290469645492843241", null, errorTarget);
      }
    }
    List<String> computerTypes = ListSequence.fromListAndArray(new ArrayList<String>(), "desktop", "server");
    if (!(ListSequence.fromList(computerTypes).contains(SPropertyOperations.getString(properties, "computerType")))) {
      {
        MessageTarget errorTarget = new NodeMessageTarget();
        errorTarget = new PropertyMessageTarget("computerType");
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(properties, "Computer Type is invalid", "r:03143f03-46ae-4107-a067-34f5026aa223(org.campagnelab.bdval.typesystem)", "2366055488404802375", null, errorTarget);
      }
    }
    if (!(Properties_Behavior.call_checkFloat_3976565827575914039(properties, SPropertyOperations.getString(properties, "foldChangePhi")))) {
      {
        MessageTarget errorTarget = new NodeMessageTarget();
        errorTarget = new PropertyMessageTarget("foldChangePhi");
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(properties, "Fold Change Feature Selection must be a number", "r:03143f03-46ae-4107-a067-34f5026aa223(org.campagnelab.bdval.typesystem)", "3976565827575976951", null, errorTarget);
      }
    }
    if (!(Properties_Behavior.call_checkFloat_3976565827575914039(properties, SPropertyOperations.getString(properties, "ttestAlpha")))) {
      {
        MessageTarget errorTarget = new NodeMessageTarget();
        errorTarget = new PropertyMessageTarget("ttestAlpha");
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(properties, "T-test Feature Selection must be a number", "r:03143f03-46ae-4107-a067-34f5026aa223(org.campagnelab.bdval.typesystem)", "3976565827575986461", null, errorTarget);
      }
    }
  }

  public String getApplicableConceptFQName() {
    return "org.campagnelab.bdval.structure.Properties";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConcept().getQualifiedName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }

  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }
}
