package org.campagnelab.bdval.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.util.MacrosFactory;
import jetbrains.mps.intentions.IntentionDescriptor;

public class ProstateExample_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public ProstateExample_Intention() {
  }

  public String getConcept() {
    return "org.campagnelab.bdval.structure.Project";
  }

  public String getPresentation() {
    return "ProstateExample";
  }

  public String getPersistentStateKey() {
    return "org.campagnelab.bdval.intentions.ProstateExample_Intention";
  }

  public String getLanguageFqName() {
    return "org.campagnelab.bdval";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:f3ea1e25-aab8-445d-9fb9-090b3b3258bf(org.campagnelab.bdval.intentions)", "4971583211590069774");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new ProstateExample_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Show Prostate Example";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      SPropertyOperations.set(node, "name", "Prostate Example");

      SNode properties = SLinkOperations.getTarget(node, "properties", true);
      SPropertyOperations.set(SLinkOperations.setNewChild(properties, "outputDirectory", "org.campagnelab.bdval.structure.Directory"), "directoryLocation", System.getProperty("user.home"));
      SPropertyOperations.set(SLinkOperations.setNewChild(properties, "bdvalDirectory", "org.campagnelab.bdval.structure.Directory"), "directoryLocation", MacrosFactory.getGlobal().expandPath("org.campagnelab.bdval.home"));
    }

    public IntentionDescriptor getDescriptor() {
      return ProstateExample_Intention.this;
    }
  }
}
