package org.campagnelab.bdval.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import org.jetbrains.mps.openapi.model.SNode;
import org.campagnelab.bdval.behavior.DataSet_Behavior;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_2125124408384843456(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386290223(final PropertyMacroContext _context) {
    return "${ant.file." + SPropertyOperations.getString(_context.getNode(), "name").replaceAll("\\s", "");
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386345809(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "properties", true), "bdvalLocation") + "/buildsupport/build.xml";
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386492210(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getBoolean(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "properties", true), "approach", true), "enableFlooring"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386422321(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "properties", true), "approach", true), "externalRepeats"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386469559(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "properties", true), "approach", true), "externalFolds"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386508182(final PropertyMacroContext _context) {
    final Wrappers._T<String> numFeatures = new Wrappers._T<String>("");
    ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "properties", true), "approach", true), "numFeatures", true)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode number) {
        numFeatures.value = numFeatures.value + "," + SPropertyOperations.getInteger(number, "value");
      }
    });
    return numFeatures.value;
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386578716(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "properties", true), "approach", true), "maxIntermediateFeatures"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386655251(final PropertyMacroContext _context) {
    return "do." + DataSet_Behavior.call_getName_290469645480322571(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386672505(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getBoolean(_context.getNode(), "normalTarget"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386691000(final PropertyMacroContext _context) {
    final Wrappers._T<String> allDatasets = new Wrappers._T<String>("");
    ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "dataset", true)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode dataset) {
        allDatasets.value = allDatasets.value + " " + DataSet_Behavior.call_getName_290469645480322571(dataset);
      }
    });
    return allDatasets.value;
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386645805(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "properties", true), "bdvalLocation") + "/data/bdval.xml";
  }

  public static Object propertyMacro_GetPropertyValue_2125124408379589107(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386241833(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Iterable<SNode> sourceNodesQuery_2125124408386653548(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "dataset", true);
  }

  public static Iterable<SNode> sourceNodesQuery_2125124408379582228(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "properties", true), "approach", true), "classification", true);
  }

  public static Iterable<SNode> sourceNodesQuery_2125124408386233196(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "properties", true), "approach", true), "featureSelection", true);
  }
}
