package org.campagnelab.bdval.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import org.jetbrains.mps.openapi.model.SNode;
import org.campagnelab.bdval.behavior.DataSet_Behavior;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import jetbrains.mps.generator.template.MappingScriptContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import org.campagnelab.bdval.behavior.Project_Behavior;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static boolean baseMappingRule_Condition_5136529682723891088(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "proceed");
  }

  public static Object propertyMacro_GetPropertyValue_2125124408384843456(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386290223(final PropertyMacroContext _context) {
    return "${ant.file." + SPropertyOperations.getString(_context.getNode(), "name") + "}";
  }

  public static Object propertyMacro_GetPropertyValue_8381115952226070471(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "properties", true), "bdvalDirectory", true), "directoryLocation");
  }

  public static Object propertyMacro_GetPropertyValue_1847053361490323918(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "properties", true), "tagDescription");
  }

  public static Object propertyMacro_GetPropertyValue_4027829922712548839(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getBoolean(SLinkOperations.getTarget(_context.getNode(), "approach", true), "evaluateStatistics"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386422321(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "approach", true), "externalRepeats"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386469559(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "approach", true), "externalFolds"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386508182(final PropertyMacroContext _context) {
    final Wrappers._T<String> numFeatures = new Wrappers._T<String>("");
    ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "numberOfFeatures", true)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode number) {
        numFeatures.value = numFeatures.value + "," + SPropertyOperations.getInteger(number, "value");
      }
    });
    return numFeatures.value.substring(1);
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386578716(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "maxIntermediateFeatures"));
  }

  public static Object propertyMacro_GetPropertyValue_1870354875263047230(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "ttest", true), "alpha");
  }

  public static Object propertyMacro_GetPropertyValue_4989762282936359621(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "svmIterative", true), "ratio");
  }

  public static Object propertyMacro_GetPropertyValue_4989762282927789736(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "geneticAlgorithm", true), "wrapperPopulationSize"));
  }

  public static Object propertyMacro_GetPropertyValue_4989762282927865816(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "geneticAlgorithm", true), "wrapperNumberIterations"));
  }

  public static Object propertyMacro_GetPropertyValue_4989762282927893143(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "geneticAlgorithm", true), "performance", true), "name");
  }

  public static Object propertyMacro_GetPropertyValue_4989762282927937845(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "geneticAlgorithm", true), "internalCVFolds"));
  }

  public static Object propertyMacro_GetPropertyValue_4989762282927972549(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "geneticAlgorithm", true), "internalCVFolds"));
  }

  public static Object propertyMacro_GetPropertyValue_4989762282938251881(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "geneticAlgorithm", true), "ratio");
  }

  public static Object propertyMacro_GetPropertyValue_6380268605258498167(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "minMax", true), "observations"));
  }

  public static Object propertyMacro_GetPropertyValue_4989762282951694400(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "permutation", true), "alpha");
  }

  public static Object propertyMacro_GetPropertyValue_3649519271367157323(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "foldchange", true), "phi");
  }

  public static Object propertyMacro_GetPropertyValue_8241402136310390495(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "kendallTau", true), "ratio");
  }

  public static Object propertyMacro_GetPropertyValue_4989762282962689461(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "coxReg", true), "alpha");
  }

  public static Object propertyMacro_GetPropertyValue_6380268605260340968(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "savedGenelist", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6380268605260365755(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "savedGenelist", false), "name") + " --gene-list-file " + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "savedGenelist", false), "file", true), "fileLocation");
  }

  public static Object propertyMacro_GetPropertyValue_4989762282957593995(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "featureSelectionInfo", true), "featureSelectionProperties", true), "pathways", true), "aggregationMethod", true), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3649519271348591714(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getBoolean(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "approach", true), "classificationInfo", true), "classificationProperties", true), "svmProperties", true), "probabilisticSVM"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386655251(final PropertyMacroContext _context) {
    return "do." + DataSet_Behavior.call_getName_290469645480322571(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386672505(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getBoolean(_context.getNode(), "run"));
  }

  public static Object propertyMacro_GetPropertyValue_2125124408386691000(final PropertyMacroContext _context) {
    final Wrappers._T<String> allDatasets = new Wrappers._T<String>("");
    ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "dataset", true)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode dataset) {
        allDatasets.value = allDatasets.value + " " + DataSet_Behavior.call_getName_290469645480322571(dataset);
      }
    });
    return allDatasets.value;
  }

  public static Object propertyMacro_GetPropertyValue_1870354875263664529(final PropertyMacroContext _context) {
    return String.valueOf(SPropertyOperations.getBoolean(_context.getNode(), "featureSelectionFold"));
  }

  public static Object propertyMacro_GetPropertyValue_1870354875263664539(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "sequenceFile");
  }

  public static Object propertyMacro_GetPropertyValue_1870354875263664556(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "allClassifierParameters");
  }

  public static Object propertyMacro_GetPropertyValue_1870354875263664565(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "otherOptions");
  }

  public static Object propertyMacro_GetPropertyValue_4671749543985197235(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8241402136315226201(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "properties", true), "outputDirectory", true), "directoryLocation") + "/" + SPropertyOperations.getString(_context.getNode(), "name") + "/" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "properties", true), "directoryName") + "/memo/memo.properties";
  }

  public static Object propertyMacro_GetPropertyValue_531337572953212163(final PropertyMacroContext _context) {
    return "runner_" + SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Iterable<SNode> sourceNodesQuery_6380268605260307875(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "dataset", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (SLinkOperations.getTarget(it, "otherFiles", true) != null);
      }
    }).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, "otherFiles", true);
      }
    }).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getTargets(it, "genelistFiles", true);
      }
    });
  }

  public static Iterable<SNode> sourceNodesQuery_2125124408386653548(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "dataset", true);
  }

  public static Iterable<SNode> sourceNodesQuery_1870354875263664572(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "approach", true), "modelToGenerate", true);
  }

  public static void mappingScript_CodeBlock_6752420586317910245(final MappingScriptContext _context) {
    ListSequence.fromList(SModelOperations.getNodes(_context.getModel(), "org.campagnelab.bdval.structure.Project")).visitAll(new IVisitor<SNode>() {
      public void visit(SNode project) {
        Project_Behavior.call_setup_7860773101052430949(project);
        if (SPropertyOperations.getBoolean(project, "proceed")) {
          Project_Behavior.call_generateAllFiles_290469645456423260(project);
        }
      }
    });
  }
}
